heroku ps:copy registerPlayer.csv
heroku ps:copy gameInfo.csv
heroku ps:copy joinGame.csv
heroku ps:copy startInfo.csv
heroku ps:copy atHomeBeacon.csv
heroku ps:copy playerUpdate.csv
heroku ps:copy newTarget.csv
heroku ps:copy exchangeRequest.csv
heroku ps:copy exchangeResponse.csv
heroku ps:copy expose.csv
heroku ps:copy intercept.csv
heroku ps:copy missionUpdate.csv
heroku ps:copy endInfo.csv
